(package "flymake-phpcs"
         "1.0.5"
         "Flymake handler for PHP to invoke PHP-CodeSniffer")

(website-url "https://github.com/illusori/emacs-flymake-phpcs")
(keywords "")

(package-file "flymake-phpcs.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "melpa")
(source "gnu")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
